name: manual build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

env:
  BUILD_PYTHON_VERSION: 3.9
  BUILD_POETRY_VERSION: 1.1.5

jobs:
  build_python:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}

      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Build project for distribution
        run: poetry build

      - name: Save release python requirements
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_reqs
          path: requirements.txt

      - name: Save release python packages
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_python
          path: dist

  build_binaries_mac:
    needs: build_python
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Checkout for spec if old tag
        if: hashFiles('evernote-backup.spec') == ''
        uses: actions/checkout@v2
        with:
          path: latest

      - name: Add spec if old tag
        if: hashFiles('evernote-backup.spec') == ''
        run: mv latest/evernote-backup.spec ./

      - name: Get tag version
        run: echo "TAG_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Load release python requirements
        uses: actions/download-artifact@v2
        with:
          name: release_dist_reqs

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller for macos
        run: pyinstaller evernote-backup.spec

      - name: Make directory for bins
        run: mkdir dist_bin

      - name: Pack up binary for macos
        run: zip -q -j dist_bin/bin_evernote_backup_${TAG_VERSION}_macos_x64.zip ./dist/evernote-backup

      - name: Save release binaries for macos x64
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_bin_macos_x64
          path: dist_bin

  build_binaries:
    needs: build_python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
        arch: [32, 64]
        include:
          - os: windows
            image: "cdrx/pyinstaller-windows"
          - os: linux
            image: "cdrx/pyinstaller-linux"
          - arch: 32
            arch_code: "x86"
            image_tag: "python3-32bit"
          - arch: 64
            arch_code: "x64"
            image_tag: "python3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Checkout for spec if old tag
        if: hashFiles('evernote-backup.spec') == ''
        uses: actions/checkout@v2
        with:
          path: latest

      - name: Add spec if old tag
        if: hashFiles('evernote-backup.spec') == ''
        run: mv latest/evernote-backup.spec ./

      - name: Get tag version
        run: echo "TAG_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Load release python requirements
        uses: actions/download-artifact@v2
        with:
          name: release_dist_reqs

      - name: Build binary for ${{ matrix.os }} ${{ matrix.arch_code }}
        env:
          IMAGE: ${{ matrix.image }}
          IMAGE_TAG: ${{ matrix.image_tag }}
        run: docker run -v "$(pwd):/src/" ${IMAGE}:${IMAGE_TAG}

      - name: Make directory for bins
        run: mkdir dist_bin

      - name: Pack up binary for windows
        if: matrix.os == 'windows'
        env:
          BUILD_ARCH: ${{ matrix.arch_code }}
        run: zip -q -j dist_bin/bin_evernote_backup_${TAG_VERSION}_win_${BUILD_ARCH}.zip ./dist/windows/evernote-backup.exe

      - name: Pack up binary for linux
        if: matrix.os == 'linux'
        env:
          BUILD_ARCH: ${{ matrix.arch_code }}
        run: tar -zcvf dist_bin/bin_evernote_backup_${TAG_VERSION}_linux_${BUILD_ARCH}.tar.gz -C ./dist/linux evernote-backup

      - name: Save release binaries for ${{ matrix.os }} ${{ matrix.arch_code }}
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_bin_${{ matrix.os }}_${{ matrix.arch_code }}
          path: dist_bin
